### ISSUE TITLE
Update to WNTR 0.2.2.1

### ISSUE THREAD

**Issue by lrntct** [conda-forge/wntr-feedstock#10]
Hi, thanks for your work!

The current version on conda-forge is 0.2.1 (from Aug 13, 2019), while the last release on PyPI is 0.2.2.1.
Is there a plan to update the conda-forge package to the last release?

**Comment by michaelbynum** [comment]
Yes, we intend to update the conda-forge package.

**Comment by michaelbynum** [comment]
Done.
